GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcwMjg0NjY2N30.b9W3YwgZuZaRTbX2LgWYDrSwhNHuJkO-FD0fd7HNmmI
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle"
}